name: WebAppTerraform
summary: This is a deployment of an Azure Web App using Terraform.
description: Deploys an App Service Plan and Web App for hosting web applications.
templatePath: main.tf
runner: "adeterraformimage.azurecr.io/ade:latest"
