name: AzureAIFoundryTerraform
summary: This is a deployment of an Azure AI Foundry environment using Terraform.
description: Deploys a foundational environment for AI services including Key Vault and supporting resources.
templatePath: main.tf
parameters:
- id: "resource_group_location"
  name: "Location"
  description: "Azure region to deploy the resources"
  type: "string"
  default: "eastus"
- id: "resource_group_name_prefix"
  name: "Resource Group Prefix"
  description: "Prefix of the resource group name that's combined with a random ID"
  type: "string"
  default: "rg"
runner: "adeterraformimage.azurecr.io/ade:latest"
