name: ContainerAppTerraform
summary: This is a deployment of an Azure Container App using Terraform.
description: Deploys an Azure Container App Environment with Azure Container App.
templatePath: main.tf
parameters:
- id: "resource_group_location"
  name: "Location"
  description: "Azure region to deploy the resources"
  type: "string"
  default: "eastus"
- id: "resource_group_name_prefix"
  name: "Resource Group Prefix"
  description: "Prefix of the resource group name that's combined with a random ID"
  type: "string"
  default: "rg"
- id: "log_analytics_workspace_sku"
  name: "Log Analytics Workspace SKU"
  description: "Log analytics workspace SKU"
  type: "string"
  default: "PerGB2018"
- id: "log_analytics_workspace_retention_in_days"
  name: "Log Retention Days"
  description: "Log analytics workspace retention in days"
  type: "number"
  default: "30"
- id: "container_app_revision_mode"
  name: "Container App Revision Mode"
  description: "Container app revision mode"
  type: "string"
  default: "Single"
  allowed:
    - "Single"
    - "Multiple"
- id: "container_name"
  name: "Container Name"
  description: "Container name"
  type: "string"
  default: "examplecontainerapp"
- id: "container_image"
  name: "Container Image"
  description: "Container image"
  type: "string"
  default: "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"
- id: "container_cpu"
  name: "Container CPU"
  description: "Container CPU cores"
  type: "string"
  default: "0.25"
- id: "container_memory"
  name: "Container Memory"
  description: "Container memory allocation"
  type: "string"
  default: "0.5Gi"
runner: Terraform
