name: AppServiceTerraform
summary: This is a deployment of an Azure App Service using Terraform.
description: Deploys an App Service Plan and App Service for hosting web applications.
templatePath: main.tf
parameters:
- id: "resource_group_location"
  name: "Location"
  description: "Azure region to deploy the resources"
  type: "string"
  default: "eastus"
- id: "resource_group_name_prefix"
  name: "Resource Group Prefix"
  description: "Prefix of the resource group name that's combined with a random ID"
  type: "string"
  default: "rg"
- id: "app_service_plan_sku_tier"
  name: "App Service Plan Tier"
  description: "The tier of the App Service Plan"
  type: "string"
  default: "Standard"
  allowed:
    - "Free"
    - "Shared"
    - "Basic"
    - "Standard"
    - "Premium"
    - "PremiumV2"
    - "PremiumV3"
    - "Isolated"
    - "IsolatedV2"
- id: "app_service_plan_sku_size"
  name: "App Service Plan Size"
  description: "The size of the App Service Plan"
  type: "string"
  default: "S1"
- id: "app_service_dotnet_framework_version"
  name: ".NET Framework Version"
  description: "The .NET Framework version for the App Service"
  type: "string"
  default: "v4.0"
- id: "app_service_scm_type"
  name: "Source Control Type"
  description: "The source control method for the App Service"
  type: "string"
  default: "LocalGit"
  allowed:
    - "LocalGit"
    - "GitHub"
    - "BitbucketGit"
    - "BitbucketHg"
runner: "adeterraformimage.azurecr.io/ade:latest"
