name: AzureFunctionsTerraform
summary: This is a deployment of an Azure Functions App using Terraform.
description: Deploys an Azure Functions App with Consumption plan, storage account, and application insights monitoring.
templatePath: main.tf
parameters:
- id: "resource_group_location"
  name: "Location"
  description: "Azure region to deploy the resources"
  type: "string"
  default: "eastus"
- id: "resource_group_name_prefix"
  name: "Resource Group Prefix"
  description: "Prefix of the resource group name that's combined with a random ID"
  type: "string"
  default: "rg"
- id: "sa_account_tier"
  name: "Storage Account Tier"
  description: "The tier of the storage account"
  type: "string"
  default: "Standard"
- id: "sa_account_replication_type"
  name: "Storage Account Replication"
  description: "The replication type of the storage account"
  type: "string"
  default: "LRS"
  allowed:
    - "LRS"
    - "GRS"
    - "RAGRS"
    - "ZRS"
- id: "runtime_name"
  name: "Runtime Name"
  description: "The name of the language worker runtime"
  type: "string"
  default: "node"
  allowed:
    - "dotnet-isolated"
    - "java"
    - "node"
    - "powershell"
    - "python"
- id: "runtime_version"
  name: "Runtime Version"
  description: "The version of the language worker runtime"
  type: "string"
  default: "20"
runner: "adeterraformimage.azurecr.io/ade:latest"
